name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn jinja2 python-multipart pydantic
        pip install pytest httpx pytest-cov
        
    - name: Run tests
      run: |
        pytest --cov=. --cov-report=term-missing --cov-report=xml
        
    - name: Display coverage summary
      run: |
        coverage report --show-missing