name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        uv sync --dev
    - name: Add venv to PATH
      run: |
        echo ".venv/bin" >> $GITHUB_PATH
    - name: Debug: List current directory
      run: |
        ls -la
    - name: Debug: List .venv/bin directory
      run: |
        ls -la .venv/bin
    - name: Debug: Print PATH
      run: |
        echo $PATH
    - name: Run tests and generate coverage report
      run: |
        .venv/bin/pytest --cov=. --cov-report=term-missing
    - name: Display coverage summary
      run: |
        echo "::notice title=Coverage Summary::"
        .venv/bin/pytest --cov=. --cov-report=term-missing | grep "TOTAL"
